### PR TITLE
[WIP] Add Meetup API integration

### PR DESCRIPTION
**Pull request by kevincharm**
The code can use some cleaning up but the basic functionality is there. We need to poll Meetup for the latest event every 15 minutes or so and update the channel topic to address #4.

### CODE REVIEW

**Comment by karlbright** [comment]
15 minutes seems like a short time? It might be best just to do this every 12 hours or so with the option of a manual update?

**Comment by luke-john** [comment]
If we are going to use minimal module config files it might help to split them out into a config folder.

lib/meetup.js -> config/meetup.js
lib/slack.js -> config/slack.js // discussed in #12

**Comment by kevincharm** [comment]
@luke-john Yeah that sounds good. I'm just gonna do the PR like this first then I think it would be good if 1 person does the re-arranging to be consistent. What do you think?

**Comment by luke-john** [comment]
👍 sounds good.

**Comment by karlbright** [comment]
Do you think we can hold off on this once we have the test stuff merged in and add tests for this?

**Comment by kevincharm** [comment]
Yeah, can do. I'll probably need some help writing useful tests for it.

**Comment by karlbright** [comment]
Keen to see this implemented with botkit Slack App implementation once merged. I was thinking about how to handle external services and thinking it's probably best to place them inside a `lib/services` directory. Just brain dumping that here for future use.

**Comment by karlbright** [comment]
Closing this. We should look at a new PR once we have changes for new implementation.

**Pull request closed without merging**
